include ../Makefile.arch
include ../Makefile.common1

#------------------------------------------------------------------------------
COMPILE_AS=lib
WHICH_OTHER_SHARED_LIBRARIES_ARE_NEEDED_TO_COMPILE=-L$(PATH_TO_SHARED_LIBRARIES_FROM_THIS_PACKAGE) # ex: add -lBlah for Blah library
#------------------------------------------------------------------------------

include ../Makefile.common2
