# Makefile for all the folders
#
#
# Author: Adrian Buzatu, 25 Oct 2012

all:
	@echo " " && make -C HelperROOT
	@echo " " && make -C testROOT
	@echo " " && echo "done: make for all."
clean:
	@echo " " && make clean -C HelperROOT
	@echo " " && make clean -C testROOT
	@rm -f *~
	@rm -f \#*
	@rm -f *.pdf *.eps *.ps *.gif *.png
	@echo " " && echo "done: make clean for all."
